### PR TITLE
trying to begin to list courses

### PR DESCRIPTION
**Pull request by hcientist**
Is this anywhere close? If it's bad, i'll stay out of the way.

### CODE REVIEW

**Comment by nwself** [comment]
Reasonable but I think we need to list Enrollments for the "list user's courses" endpoint.

See my attempt here https://github.com/JMU-CIME/CPR-Music-Backend/blob/main/teleband/courses/api/serializers.py#L14

But now I see you are using HyperlinkedModelSerializers which is probably better, will switch to that

**Comment by nwself** [comment]
Actually. So, I have an endpoint that tells you your courses like this

```
    {
        "course": {
            "name": "Example Course",
            "slug": "example-course"
        },
        "instrument": {
            "name": "Piano",
            "transposition": "Concert Pitch"
        },
        "role": "Teacher"
    }
```

I think the only change for this to be ideal is to have `url` instead of `slug` in the course so that you don't have to compose the API URL for the course? AKA no need to query detail on instrument or role?

**Comment by nwself** [comment]
Changed to the following in b74107268a246bbe4ce4d8cd6064c030dffacd86

```
    {
        "course": {
            "name": "Example Course",
            "owner": "http://localhost:8000/api/users/admin/",
            "url": "http://localhost:8000/api/courses/example-course/"
        },
        "instrument": {
            "name": "Piano",
            "transposition": "Concert Pitch"
        },
        "role": "Teacher"
    }
```

Possibly we need owner name in here too?

**Comment by hcientist** [comment]
All this looks awesome! Question: if I understand [django.urls.reverse](

**Pull request closed without merging**
